defaults:
  - _self_
  - model: general
  - data: general
  - algorithm: general
  - train: general

algorithm:
  learning_rate: 0.1
  optimizer: SGD

train:
  num_epochs: 5
  #  snapshot_path: snapshot/snapshot.pth
  save_interval: 20
  evaluate_interval_steps: 40
  evaluate_interval_epochs: 1
  seed: 415
  calculate_eigenvalue_at_step: 2000

data:
  batch_size: 128
  test_batch_size: 1000

model:
  T: 1


wandb:
  project: avila
  entity: superposed-tree
  mode: online
  group: ode_group

hydra:
  run:
    dir: hydra_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

  #  mode: RUN
  mode: MULTIRUN
  sweeper:
    params:
      model.T: 1



