defaults:
  - /model: gpt2
  - /data: general
  - /algorithm: general
  - /train: gpt2
  - /wandb: general
  - _self_

data:
  batch_size: 32
  test_batch_size: 32

algorithm:
  learning_rate: 0.01

wandb:
  project: gpt2
  entity: superposed-tree
  mode: offline
  group: gpt2_group

train:
  num_epochs: 100
  #  snapshot_path: snapshot/snapshot.pth
  save_interval_epochs: 5
  save_interval_steps: 1000
  evaluate_interval_steps: 99999
  evaluate_interval_epochs: 1
  seed: 415
  device: "cuda"